name: "OpenVPN Connect for DI PUC-Rio servers"
description: "Connect to DI PUC-Rio servers"
branding:
  icon: "lock"
  color: "yellow"
inputs:
  config_file:
    description: "Location of OpenVPN client config file"
    required: true
  username:
    description: "Username"
    required: true
  password:
    description: "Password"
    required: true
  private_key_password:
    description: "Private Key Password"
    required: true
  tls_auth_key:
    description: "Pre-shared group key for TLS Auth"
    required: false
  echo_config:
    description: "Print the OpenVPN configuration file"
    required: false
    default: "true"
runs:
  using: "node20"
  main: "dist/index.js"
  post: "dist/index.js"
