name: Test
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
jobs:
  show-context:
    runs-on: ubuntu-latest
    steps:
      - name: Show github context object
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
  test:
    runs-on: ubuntu-latest
    name: Typical Usage of OpenVPN
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
      - name: Connect to VPN
        uses: "./"
        with:
          username: ${{ secrets.OVPN_USERNAME }}
          password: ${{ secrets.OVPN_PASSWORD }}
          private_key_password: ${{ secrets.OVPN_PK_PASSWORD }}
          private_key_filename: ${{ secrets.OVPN_PK_FILENAME }}
        env:
          CONFIG_FILE: ${{ secrets.OVPN_CONFIG_FILE }}
          PRIVATE_KEY_FILE: ${{ secrets.OVPN_PRIVATE_KEY_FILE }}
